
omnichannel_kv_rg                    = "rg-omnichannel-security-prod"
salesforceapimauthendpoint           = "https://api.segrocers.com/sfmcauthservice/"
salesforceapimbaseendpoint           = "https://api.segrocers.com/sfmcservice/"
cache_server                         = "redis-omnichannel-seg-prod.redis.cache.windows.net:6380"
base_url_ee                          = "https://api.segrocers.com/EE"
base_url_campaigns_ee                = "https://api.segrocers.com/EagleEyeCampaignsAPI"
redis_connection_timeout             = ",connectTimeout=15000"
digitalmktg_vault_name                = "DigitalMktg-Vault-PROD"
digitalmktg_vault_resource_group_name = "Security"