digitalmktg_vault_name                 = "DigitalMktg-Vault-QA"
digitalmktg_vault_resource_group_name  = "ActiveDirectory-DEV"
salesforceapimauthendpoint             = "https://qa-api.segrocers.com/sfmcauthservice/"
salesforceapimbaseendpoint             = "https://qa-api.segrocers.com/sfmcservice/"
seg_key                                = "QA_Eagle_Eye_Account_ID"
segclientid                            =  "0yua73njn9z82zvi158d73th"
segclientsecret                        =  "efb4ZlZdgjQbcnwfgSijz9uE"
ocpapimsubscriptionkey                 = "2a8a770db66e458e9ba4596a31087c0f"