
omnichannel_kv_rg                    = "rg-omnichannel-security-qa"
salesforceapimauthendpoint           = "https://qa-api.segrocers.com/sfmcauthservice/"
salesforceapimbaseendpoint           = "https://qa-api.segrocers.com/sfmcservice/"
cache_server                         = "redis-omnichannel-seg-qa.redis.cache.windows.net:6380"
base_url_ee                          = "https://qa-api.segrocers.com/EE"
base_url_campaigns_ee                = "https://qa-api.segrocers.com/EagleEyeCampaignsAPI"
redis_connection_timeout             = ",connectTimeout=15000"
digitalmktg_vault_name                = "DigitalMktg-Vault-QA"
digitalmktg_vault_resource_group_name = "ActiveDirectory-DEV"
